### ISSUE TITLE
I have only two rows,it can not guess columns;but more then 5 ,it can 

### ISSUE THREAD

**Issue by qingcaol** [shun0102/embulk-parser-jsonl#11]
two rows:
{"id":1,"ds_name":"wechat_text","ds_type":1,"keyword":"微信","sources_illustrate":"微信","description":"微信公众号","owner_id":0,"owner":"东东","accredit":"东东","storage_platform_format":2,"delimiter":"","group_id":1,"complete_rate":35.0,"health_rate":false,"displayorder":0.0,"creator_id":0,"delete_flag":false,"create_time":"2016-11-09T16:32:05.000+0800","_timestamp":"2016-11-09T16:52:00.000+0800"}
{"id":1,"ds_name":"wechat_text","ds_type":1,"keyword":"微信","sources_illustrate":"微信","description":"微信公众号","owner_id":0,"owner":"东东","accredit":"东东","storage_platform_format":2,"delimiter":"","group_id":1,"complete_rate":35.0,"health_rate":false,"displayorder":0.0,"creator_id":0,"delete_flag":false,"create_time":"2016-11-09T16:32:05.000+0800","_timestamp":"2016-11-09T16:52:00.000+0800"}

config.yml:
in:
  type: file
  path_prefix: /Users/changqing/embulk/try1/csv/sample_
  parser:
    type: jsonl
out: {type: stdout}

embulk guess -g jsonl config.yml -o guessed.yml
get guessed.yml:
in:
  type: file
  path_prefix: /Users/changqing/embulk/try1/csv/sample_
  parser: {type: jsonl, charset: UTF-8, newline: CRLF}
out: {type: stdout}

guessed.yml not include columns，why？？
if file includes more then 5 rows ,it can get columns;

**Comment by muga** [comment]
Hi @qingcaol,

It seems that the parser doesn't guess (suggest) parser configs if the json files have less than or equal to 3 lines. Because the accuracy of the suggestion is improved. 
https://github.com/shun0102/embulk-parser-jsonl/blob/master/lib/embulk/guess/jsonl.rb#L21

We could take an approach for suggesting the parser config forcedly even though the file has few lines only but, not implemented yet.

**Comment by yoichi** [comment]
What does happen if we remove the line "return {} if rows.size <= 3" introduced in https://github.com/shun0102/embulk-parser-jsonl/commit/67c959e293d61a094ed6c0749a116f66673fd237?

**Comment by muga** [comment]
@yoichi Sorry for late reply. In that case, the parser suggests Embulk config by a few rows (lines). The suggested config can be used for the same JSON file. But, the config might not have high reusability so much. It might not be used for other similar JSON files. 

Anyway, I'm OK to remove this condition. @shun0102 if you don't have any concerns about it, I will remove it.

**Comment by hiro-koba** [comment]
Hi @muga ,
I'm also facing the same problem when I run `guess` command to JSONLines file which only includes  1 line.
(In my case, `guess` command's source JSONLines files sometimes have only few lines)

Could you please remove this condition? https://github.com/shun0102/embulk-parser-jsonl/blob/master/lib/embulk/guess/jsonl.rb#L21
